### ISSUE TITLE
crashing when opening advancements menu 

### ISSUE THREAD

**Issue by ifbw** [diskria-minecraft/atd#12]
so, the title says it all, almost. so i added around 20 extra mods for it to be a bit more fun and interesting, updated them all after a while because some had important updates and uh, it started crashing on startup telling me that the mod "AdvancementInfo" had a problem with "AchieveToDo", so i removed it. the game works fine, until i open the advancements menu. then it just crashes, happens with a few other mods/datapacks that add more achievements (except btcap). so i need help fixing this. i'll send the crash logs (the entre log from start to end).
https://mclo.gs/aEeNKg8
( all the mods are visible in the logs site )

**Comment by ifbw** [comment]
the crash error from advancements menu 
v     v     v     v     v     v      v      v      v      v

[10:42:00] [Render thread/INFO]: Loaded 450 advancements
--
1045 | [10:42:01] [Render thread/INFO]: [System] [CHAT] §eJourneyMap:§f Press [§bJ§f]
1046 | [10:42:02] [Render thread/WARN]: Unable to play empty soundEvent: minecraft:entity.salmon.ambient
1047 | [10:42:06] [Render thread/ERROR]: Unreported exception thrown!
1048 | java.lang.IllegalArgumentException: No enum constant com.diskree.achievetodo.advancements.AdvancementRoot.SOURCE
1049 | at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
1050 | at com.diskree.achievetodo.advancements.AdvancementRoot.valueOf(AdvancementRoot.java:3) ~[achievetodo-1.21.20.1.i0:0/:?]
1051 | at net.minecraft.class_454.handler$ffo000$achievetodo$createInject(class_454.java:553) ~[minecraft-1.20.1.i0:0/:?]
1052 | at net.minecraft.class_454.method_2317(class_454.java) ~[minecraft-1.20.1.i0:0/:?]
1053 | at net.minecraft.class_457.method_723(class_457.java:184) ~[minecraft-1.20.1.i0:0/:?]
1054 | at net.minecraft.class_163.method_717(class_163.java:119) ~[minecraft-1.20.1.i0:0/:?]
1055 | at net.minecraft.class_632.method_2862(class_632.java:88) ~[minecraft-1.20.1.i0:0/:?]
1056 | at net.minecraft.class_457.method_25426(class_457.java:60) ~[minecraft-1.20.1.i0:0/:?]
1057 | at net.minecraft.class_437.method_25423(class_437.java:297) ~[minecraft-1.20.1.i0:0/:?]
1058 | at net.minecraft.class_310.method_1507(class_310.java:1080) ~[minecraft-1.20.1.i0:0/:?]
1059 | at net.minecraft.class_310.method_1508(class_310.java:2013) ~[minecraft-1.20.1.i0:0/:?]
1060 | at net.minecraft.class_310.method_1574(class_310.java:1883) ~[minecraft-1.20.1.i0:0/:?]
1061 | at net.minecraft.class_310.method_1523(class_310.java:1181) ~[minecraft-1.20.1.i0:0/:?]
1062 | at net.minecraft.class_310.method_1514(class_310.java:802) ~[minecraft-1.20.1.i0:0/:?]
1063 | at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
1064 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
1065 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
1066 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
1067 | at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
1068 | at org.quiltmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:551) ~[quilt-loader-0.22.0-beta.3.jar:?]
1069 | at org.quiltmc.loader.impl.launch.knot.Knot.launch(Knot.java:84) ~[quilt-loader-0.22.0-beta.3.jar:?]
1070 | at org.quiltmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:28) ~[quilt-loader-0.22.0-beta.3.jar:?]
1071 | at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
1072 | at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130) ~[NewLaunch.jar:?]
1073 | at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
1074 | [10:42:07] [Server thread/INFO]: Stopping server
1075 | [10:42:07] [Server thread/INFO]: Saving players
1076 | [10:42:07] [Server thread/INFO]: Saving worlds

**Comment by diskria** [comment]
The AdvancementInfo mod is not supported, since AchieveToDo already has hints within the gameplay. You can check out the "Hintly Hallows" riddle to get started. Аnd any other ways to get a hint are cheating in the modpack understanding. Also, AchieveToDo mod adds a search to the advancements window, which also conflicts with AdvancementInfo.

**Comment by diskria** [comment]
Adding other advancements is also not supported in the modpack, since it balanced for BACAP only

**Comment by ifbw** [comment]
but how do you cheat, its disabled from the mod itsself. anyways, can you just give me a fix to stop the crashing when i open the advancements menu?

**Comment by diskria** [comment]
AchieveToDo mod will be crash game if AdvancementInfo mod installed bcz they conflicts altogether

**Comment by ifbw** [comment]
> AchieveToDo mod will be crash game if AdvancementInfo mod installed bcz they conflicts altogether

but i dont have it installed and it still crashes, check the log and all the mods i have

**Comment by ifbw** [comment]
ok so it turns out its one of my datapacks, made a fresh world turns out its uh. a datapack
