### ISSUE TITLE
Cannot play if cannot drag-and-drop datapack to minecraft window

### ISSUE THREAD

**Issue by istudyatuni** [diskria-minecraft/atd#13]
I'm on linux, so that's probably the reason why drag and drop for minecraft doesn't work. Where can I put this datapack manually?

Possible solutions (from my pov)

- add a button "Select datapack file" (with opening system's file selector)
- pick datapack from .minecraft/datapacks folder

**Comment by diskria** [comment]
I would like to know which file caused the problem? 
Do you have drag and drop missing in your system? 
Is the Minecraft window not responding after drag and drop?

Retry it please with disabled full screen mode.
You can manually put the file named `bacap.zip` (the correct name is required) to `.minecraft/datapacks` directory.  The mod does the same thing.

Thanks for suggestion, "Select datapack file" button will be added in 1.3 update

**Comment by istudyatuni** [comment]
> which file caused the problem?

`BlazeandCave's Advancements Pack 1.16.3.zip` from [modrinth](https://modrinth.com/datapack/blazeandcaves-advancements-pack) (currently modrinth not work), but it seems that neither file will work

> Do you have drag and drop missing in your system?

No, drag and drop works, for example, from [dolphin](https://apps.kde.org/dolphin) to browser

> Is the Minecraft window not responding after drag and drop?

No, just nothing happens, I can still click "Cancel" button

> Retry it please with disabled full screen mode.

Same in both modes

> The mod does the same thing.

I couldn't find mod, only datapack :cry: (at least on modrinth)

**Comment by diskria** [comment]
> from [modrinth](https://modrinth.com/datapack/blazeandcaves-advancements-pack)

The game checks the SHA1 of the downloaded file and ignores the file if it doesn't match, so you should click the "Download" button which will open the required file download page (it is MediaFire)

**Comment by istudyatuni** [comment]
Hmm, I tried datapack versions 1.16.2 and 1.16.3 - renamed it to bacap.zip, and both work, but their sha-1 doesn't match

**Comment by diskria** [comment]
sha-1 checks when you put file via drag and drop. If you put named file manually then sha-1 check skipped

**Comment by istudyatuni** [comment]
Additional suggestion - many people play using third party launchers like prism[^1] or modrinth launcher, these launchers can load datapacks, I think it would be nice to load these datapacks automatically

[^1]: datapacks loading are wip

**Comment by diskria** [comment]
btw ATD 1.2 is developed and supported for BACAP 1.16.2, so I not recommend to use BACAP 1.16.3 (it will be coming in ATD 1.3).

**Comment by diskria** [comment]
> load these datapacks automatically

Unfortunately the owner of BACAP has a very strict license, so I don't want to risk it

**Comment by diskria** [comment]
I believe that I can add automatic loading but only for main datapack (because owner of BACAP published it on Modrinth), but his other datapacks can still only be downloaded from PMC.

**Comment by diskria** [comment]
Ok, I did it and it will in ATD 1.3:

https://github.com/diskree/AchieveToDo/commit/bc3c4bf4857bf9d457e49c65190bffcde08048be

![image](https://github.com/diskree/AchieveToDo/assets/96978370/ba53333b-803f-454e-ab06-90d86e7eb639)
