### ISSUE TITLE
Re-check achievements count at world start/user join

### ISSUE THREAD

**Issue by istudyatuni** [diskria-minecraft/atd#14]
Use case: minecraft force stopped (laptop turned off because of battery), so achievement count drops (24 -> 19), but all completed achievements remains completed (24). For now I edited data/scoreboard.dat, but it's not perfect solution

**Comment by diskria** [comment]
Advancements can break very easily and this is a Minecraft problem or a BACAP bug, not ATD relatedd

**Comment by diskria** [comment]
I'll think about adding a autobackup mod to the modpack, for ex. https://github.com/Szum123321/textile_backup 🤔

**Comment by istudyatuni** [comment]
A possible solution could be to write the number of achievements to a file immediately after receiving the achievement, because minecraft/bacap seems to record the completion status of the achievement immediately.

**Comment by diskria** [comment]
this is not the responsibility of my project, my goal is to add locks, but what you are talking about is a fix for bacap/Minecraft

**Comment by istudyatuni** [comment]
Oh, number of completed achievements written by Minecraft? Sorry, didn't know about this
