### ISSUE TITLE
ATD 1.20.2

### ISSUE THREAD

**Issue by Degoi** [diskria-minecraft/atd#15]
Hello! Today I saw your news on modrinth, as I understand it, the modpack will become more interesting, but how will you transfer the modpack to version 1.20.4 if qfapi has not been released even for 1.20.2?

**Comment by diskria** [comment]
Hi! I just migrate core mod and modpack to fabric api, which already supports 1.20.4: https://github.com/diskree/AchieveToDo/commit/6da0faa60bed99fd75b96ed8e919527162f1f170
