### ISSUE TITLE
Bug with scissors and inventory blocked actions

### ISSUE THREAD

**Issue by Ko5atel** [diskria-minecraft/atd#24]
Hi! You recently released the ATD 1.4 build, which adds closed achievements (which is very cool), in which when opening 144 achievements you have the option to use scissors, but for some reason they can be used on sheep, and possibly other functionality

**Comment by Ko5atel** [comment]
D

**Comment by Ko5atel** [comment]
By the way, is opening your inventory with the help of a horse, a donkey and a llama without unlocking achievements a feature or not?

**Comment by diskria** [comment]
@Ko5atel Thanks for this report! Yea, this was missed during testing. I'll fix it in 1.4.1 later this week

**Comment by diskria** [comment]
Unfortunately, the fixes require changing some refactoring in the code, but I don't have any more free time, so this fix, I think, is delayed for 2.x update until at least April. 

But this bug is already fixed, so I'm closing this issue
