### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Misha4ek** [diskria-minecraft/atd#25]
Can you make trophey to not dispawn and immune to lava? Like when your inventory is full and you in nether in would be very neat.

**Comment by diskria** [comment]
AchieveToDo's goal is to add relationships between advancements and gameplay. Therefore your idea should be addressed to the BlazeandCave's community, and not to this modpack

Maybe I'll create a separate mod, but adding it to the modpack by default is not a good idea, I think

**Comment by diskria** [comment]
This is realized in my new mod ImmortalTrophies (https://modrinth.com/mod/immortaltrophies) and I add it to next update of AchieveToDo. Thanks for your idea!

**Comment by Misha4ek** [comment]
> This is realized in my new mod ImmortalTrophies (https://modrinth.com/mod/immortaltrophies) and I add it to next update of AchieveToDo. Thanks for your idea!

Absolute banger.
