### ISSUE TITLE
Help me 😭

### ISSUE THREAD

**Issue by AlmazZ07** [diskria-minecraft/atd#31]
Hello, a huge problem is not understanding riddles and even banal guides, can you tell me how to unlock the “Gifts of Hints”, with Beethoven’s riddle, I’m already crazy

**Comment by diskria** [comment]
You need to be near the "portal" in the Ancient City, with effect of invisibility and play music disc 5 on jukebox. You will learn further actions from the Riddle tab.

This mechanic will be replaced in a future update with something easier to use. So this secret can be revealed.

**Comment by lioxite** [comment]
Hello,i have some problems.How i need activate portal ? 
 
![image](https://github.com/diskree/AchieveToDo-ModPack/assets/172891256/f7c1ebae-8748-4ebb-a4f4-5e2cf1bc0c5e)
