### ISSUE TITLE
ATD 1.2 1.20.1

### ISSUE THREAD

**Issue by lioxite** [diskria-minecraft/atd#32]
Hello,i have some problems.How i need activate portal ?
![image](https://github.com/diskree/AchieveToDo-ModPack/assets/172891256/d28bc562-5768-4871-b798-b472b8e1c07b)

**Comment by diskria** [comment]
Hi! This already answered here: https://github.com/diskree/AchieveToDo-ModPack/issues/31#issuecomment-2169129355
