### ISSUE TITLE
what im doing wrong 

### ISSUE THREAD

**Issue by lioxite** [diskria-minecraft/atd#33]
Hello again! As i understood its mad scientist on potion tab.Its right? If yes what i need do 
![2024-06-17_19 59 10](https://github.com/diskree/AchieveToDo-ModPack/assets/172891256/a0d68bad-c2d5-4441-8013-e6d9074292d7)
![2024-06-17_19 55 18](https://github.com/diskree/AchieveToDo-ModPack/assets/172891256/183983f8-d225-4f6d-82d6-a48f66a5bf39)
![2024-06-17_19 07 39](https://github.com/diskree/AchieveToDo-ModPack/assets/172891256/07cd3ea5-9082-4249-af70-a46ad8e187aa)

**Comment by diskria** [comment]
Hi, yes, you understood right. So, portal gave a hint meaning that one of the remaining villagers for "Mad scientist" advancement is fletcher. Do you mean that you have already obtained this?

UPD: answered in discord
