### ISSUE TITLE
I can't create a new world

### ISSUE THREAD

**Issue by Utatto** [diskria-minecraft/atd#34]
Hello, I've played with this build before and had no problems creating the world. But now I want to create a new world and I get this error like in the photo.
I already tried to do what the assembly itself told me to do and still nothing worked. Even though I installed the required datapack and transferred it to Minecraft, even if I rip it out randomly, nothing works. Help me please.

![ошибка](https://github.com/user-attachments/assets/52eea571-5eac-4695-8eaf-3f97a536e977)

**Comment by diskria** [comment]
please make sure that you downloaded the datapack by the `Download` button and do not unzip anything even if it says UNZIP ME.
