### ISSUE TITLE
Wayland: The platform does not support setting the cursor position

### ISSUE THREAD

**Issue by arturamiryan** [diskria-minecraft/atd#37]
Issue: [CursorCentered Fix](https://modrinth.com/mod/3Vf97jLY) is not compatible with Linux on Wayland. Crash every time when open any inventory or chat in the game. Big stutter on Gnome.

Possible solution: Detect Linux+Wayland and disable [CursorCentered Fix](https://modrinth.com/mod/3Vf97jLY)

**Comment by diskria** [comment]
Thanks for your report! I think I will just remove this mod from the next modpack update. Actually the mod is not that important and the possible solution is taking up my time.
