### ISSUE TITLE
Баг с перетаскиванием брони | Armor Dragging Bug

### ISSUE THREAD

**Issue by LogikaCode0** [diskria-minecraft/atd#38]
Если нажимать правую кнопку мыши, то всё работает правильно — броню надеть нельзя. Однако, если зайти в инвентарь и перетащить броню на слот для её ношения она наденется.

If you right-click, everything works correctly — the armor cannot be equipped. However, if you open the inventory and drag the armor to the slot for wearing it will be equipped

![javaw_zyccHBe4gB](https://github.com/user-attachments/assets/bdd2d719-9148-42cc-82da-1bfc21fb3508)
(С использованием правой кнопки мыши | Using the right mouse button)

![image](https://github.com/user-attachments/assets/e7a2dc3d-ff56-417e-9cd3-b0b1f777ea3c)
(Броня наделась в инвентаре | The armor was equipped in the inventory)

**Comment by diskria** [comment]
Thanks for your report! In fact, this (and many other ability lock bypasses) are already fixed in the next core mod/modpack release.
