### ISSUE TITLE
Include BlazeandCave's Advancements Pack in the modpack

### ISSUE THREAD

**Issue by aninusmuffin** [diskria-minecraft/atd#7]
Some of the required datapacks/mods are available on modrinth so its not needed to download them separately.

Available as datapacks:
- https://modrinth.com/datapack/blazeandcaves-advancements-pack

Available as mods:
- https://modrinth.com/mod/terralith
- https://modrinth.com/mod/nullscape
- https://modrinth.com/mod/incendium

**Comment by diskria** [comment]
I can't include BACAP datapack would be a violation of the Cavinator's license
I can't use mods because I need datapacks format for enable/disable in world creation

**Comment by diskria** [comment]
Also, some Cavinator's datapacks are not published on Modrinth so I don't think it needs to be done selectively

**Comment by aninusmuffin** [comment]
> I can't include BACAP datapack would be a violation of the Cavinator's license

Wait can a license prohibit the use of a datapack in a modpack? (i mean as a manifest in the modrinth.index.json)

**Comment by diskria** [comment]
@Aninuscsalas I'm not very good at this, but if you read the PMC license, it seems that you can't do anything with the datapack. Totally. I think that I don't have the right to load it automatically during modpack import or before world creation, so I want the player to still perform at least some action, after knowing why it is needed, what needs to be download, as well as the ability to go to the project page.

This is essentially a violation too, but I rely on the fact that the Cavinator will not consider this a violation, given how it works... btw, I asked him about this, but he not answered me yet
